In [27]:
from sklearn.cluster import KMeans
from skimage import io
import matplotlib.pyplot as plt

In [28]:
img = io.imread('G:/Python_Learning/Python_RS/Image_Copy/Image/Landsat/NIR.tif')

In [62]:
row = img.shape[0]
col = img.shape[1]

In [66]:
X = img.reshape(row*col, 1)

In [67]:
X

array([[3311],
       [3527],
       [3537],
       ...,
       [2986],
       [2712],
       [2843]], dtype=int16)

In [68]:
kmeans = KMeans(n_clusters=4, random_state=0)
kmeans.fit(X)

KMeans(n_clusters=4, random_state=0)

In [69]:
cluster_centers = kmeans.cluster_centers_
cluster_labels = kmeans.labels_

In [70]:
cluster_centers

array([[3717.05975551],
       [ 172.5064175 ],
       [2740.59746973],
       [1483.92056014]])

In [71]:
cluster_labels

array([0, 0, 0, ..., 2, 2, 2])

In [73]:
clusterd_image= cluster_centers[cluster_labels].reshape(row, col)

In [ ]:
plt.figure(figsize=(15,15))
plt.imshow(clusterd_image)
plt.show()